#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# al-biruni-1 — Researcher (auto + deep)
# Part of the al-biruni singleton pair mesh.
# Discovers, analyzes, and synthesizes knowledge autonomously.
#
# Modes:
#   auto     — broad scan, surface-level, fast
#   deep     — focused deep-dive, exhaustive, slow
#   generate — produce research report
#
# Shares brain state via ultramesh-mem at
# ~/.cache/ultrameshai/brain-state.json
# ─────────────────────────────────────────────────────────────
set -euo pipefail
MODE="${1:-auto}"
TOPIC="${2:-}"
OUTDIR="${3:-${AL_BIRUNI_OUTDIR:-./.al-biruni/research}}"
mkdir -p "$OUTDIR"

case "$MODE" in
  auto)
    [ -z "$TOPIC" ] && { echo "USAGE: $0 auto <topic>" >&2; exit 1; }
    echo "🔍 al-biruni-1 (auto-research): $TOPIC"
    echo "topic=$TOPIC" > "$OUTDIR/_meta"
    echo "mode=auto" >> "$OUTDIR/_meta"
    echo "ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$OUTDIR/_meta"
    # Generate research outline
    cat > "$OUTDIR/outline.md" << OUTFILE
# Research: ${TOPIC}

## Scope
- Primary sources
- Secondary analysis
- Current state

## Key Questions
1. What is the core problem/idea?
2. Who are the key contributors?
3. What evidence exists?
4. What is contested?
5. What are the open questions?

## Method
- Literature survey
- Cross-reference verification
- Synthesis
OUTFILE
    echo "OUTLINE: $OUTDIR/outline.md"
    ;;

  deep)
    [ -z "$TOPIC" ] && { echo "USAGE: $0 deep <topic>" >&2; exit 1; }
    echo "🕳️ al-biruni-1 (deep-research): $TOPIC"
    echo "mode=deep" >> "$OUTDIR/_meta"
    cat > "$OUTDIR/findings.md" << OUTFILE
# Deep Findings: ${TOPIC}

## Sources Surveyed
- Academic papers
- Technical documentation
- Primary sources
- Expert interviews/corpus

## Analysis
- Hypothesis: --
- Evidence strength: --
- Contradictions: --
- Gaps: --

## Synthesis
- Core insight: --
- Implications: --
- Recommendations: --
OUTFILE
    echo "FINDINGS: $OUTDIR/findings.md"
    ;;

  generate)
    echo "📝 al-biruni-1 (generate report)"
    if [ -f "$OUTDIR/outline.md" ] || [ -f "$OUTDIR/findings.md" ]; then
      cat > "$OUTDIR/report.md" << OUTFILE
# Research Report

$(cat "$OUTDIR/outline.md" 2>/dev/null || echo "")
$(cat "$OUTDIR/findings.md" 2>/dev/null || echo "")

---
*Generated by al-biruni-1 (Researcher)*
OUTFILE
      echo "REPORT: $OUTDIR/report.md"
    else
      echo "ERROR: nothing to generate — run auto or deep first"
      exit 1
    fi
    ;;

  *)
    echo "USAGE: $0 {auto|deep|generate} [topic]"
    exit 1
    ;;
esac
